### ISSUE TITLE
eval.py isn't running as expected

### ISSUE THREAD

**Issue by Saarraaaah** [alexanderrichard/action-sets#1]
Hello there,

I have been trying to reproduce the results of your paper.
However when I reach the evaluation stage it seems that the code isn't able to locate the TruthGround files. 

In the eval.py there's these lines of code 

```
parser = argparse.ArgumentParser()
parser.add_argument('--recog_dir', default='./results')
parser.add_argument('--ground_truth_dir', default='./data/groundTruth')
args = parser.parse_args()

filelist = glob.glob(args.recog_dir + '/P*')
```

Where I think the last line should be 

`filelist = glob.glob(args.ground_truth_dir + '/P*')`

Please correct if I am wrong, because when I changed it to this the code ran successfully and I got an accuracy of 
**Evaluate 1712 video files...
frame accuracy: 0.872664**

Thanks,

**Comment by alexanderrichard** [comment]
Hi Sarah,

`filelist = glob.glob(args.recog_dir + '/P*')`
is correct. See line 46, where the files from recog directory are compared against files from the ground truth directory:
`errors, frames = recog_file(filename, args.ground_truth_dir)`
In your case, you wouldn't read any of the recognized segmentations at all.
Could you post the exact error message and maybe attach a file containing the output of `tree` invoked on you action set directory?

Kind regards,
Alex

**Comment by Saarraaaah** [comment]
Hi Alex,

I have returned the code to its original state and this is what I am getting now:
```
  File "eval.py", line 40
    print 'Evaluate %d video files...' % len(filelist)
                                     ^
SyntaxError: invalid syntax
```

For the output, can you please elaborate more.

Thanks,
Sarah

**Comment by alexanderrichard** [comment]
Ahh, I see. This is a relict from when the code was still written for python2.7. In python3, the print function uses parentheses (same issue in line 51):
`print('Evaluate %d video files...' % len(filelist))`
Thanks for pointing out the issue. It is now fixed.

**Comment by Saarraaaah** [comment]
Okay, now I'm getting the same error for the next print statement ;p which is
`print  'frame accuracy: %f' % (1.0 - float(n_errors) / n_frames)`
I had the parentheses on the next one 
`print ('frame accuracy: %f' % (1.0 - float(n_errors) / n_frames))`
but I am getting another error message.

```
Evaluate 0 video files...
Traceback (most recent call last):
  File "eval.py", line 51, in <module>
    print ('frame accuracy: %f' % (1.0 - float(n_errors) / n_frames))
ZeroDivisionError: float division by zero
```

So why does it say 0 files, and even when I wrapped this block of code in a try and catch statements, I am not getting the expected output.

Please advise.

Thank you in advance,

**Comment by alexanderrichard** [comment]
Hi Sarah,
if it says 0 video files, `glob.glob(args.recog_dir + '/P*')` returns an empty list. Whatever your recog directory is, it seems to be empty or not have any files starting with a capital P. So, either the recog dir you pass to eval does not exist or when you ran the inference, nothing was written.
Please check if the P* files exist in your recog dir. If not, maybe you didn't give the program permission to create those files while doing the inference step. You might post the output of the uni command `tree` invoked from your action-sets directory, then I might check you directory structure.

**Comment by Saarraaaah** [comment]
Hi Alex,
Thanks for the reply.
It seems the problem was with the permission as you suggested. It's running now, will close the issue once the inference and evaluation stages are complete.

As a side note, if I have some questions regrading the research paper, whom may I contact.

Thanks again

**Comment by Saarraaaah** [comment]
Hi Alex,

This is the final output I'm getting, am I on the right track?
```
Evaluate 252 video files...
frame accuracy: 0.190876
```

Waiting for your confirmation and reply regrading my previous question.

Thanks!

**Comment by alexanderrichard** [comment]
Looks good. The results in the paper are a bit higher but there may be some noise with different initializations.

If you have questions regarding the paper, feel free to write me a mail.
