### ISSUE TITLE
Dataset link for other two datasets

### ISSUE THREAD

**Issue by ChinaYi** [alexanderrichard/action-sets#2]
Hi~ Thanks for releasing your code and great work!  I would appreciate if you can help me with the features of other two datasets.

**Comment by alexanderrichard** [comment]
Hi! I graduated and do not have access to the University servers anymore. Please reach out to one of my co authors.

 
 

Gesendet: Mittwoch, 16. Dezember 2020 um 00:12 Uhr
Von: "ChinaYi" <notifications@github.com>
An: "alexanderrichard/action-sets" <action-sets@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [alexanderrichard/action-sets] Dataset link for other two datasets (#2)


 

Hi~ Thanks for releasing your code and great work! I would appreciate if you can help me with the features of other two datasets.
